ECOMMERCE_DB-- 1_create_warehouse.sql
CREATE OR REPLACE WAREHOUSE etl_wh
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE etl_wh;
show warehouses;


